name: Linux build for V 2.0
on: [push,pull_request]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
    - name: Setup Swift environment
      run: |
        wget https://swift.org/builds/swift-5.2.4-release/ubuntu2004/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-ubuntu20.04.tar.gz
        tar -zxvf swift-5.2.4-RELEASE-ubuntu20.04.tar.gz
    - name: Setup Lua environment
      run: |
        sudo apt install libreadline-dev
        curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
        tar zxf lua-5.3.5.tar.gz
        cd lua-5.3.5
        sudo make linux test
        sudo make install
    - name: COM Cpp files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Cpp/main.cpp;g++ main.cpp -o LeapYearCheakLinuxCpp
    - name: COM C files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/C/main.c;gcc main.c -o LeapYearCheakLinuxC
    - name: COM Java files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Java/LeapYearCheak.java;javac LeapYearCheak.java
    - name: COM Swift files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Swift/main.swift;./swift-5.2.4-RELEASE-ubuntu20.04/usr/bin/swiftc main.swift
    - name: TEST Python files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Python/main.py
        echo -e "1 \n" | python3 main.py
        echo -e "2020 \n" | python3 main.py
    - name: TEST Go files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Go/main.go
        echo -e "1 \n" | go run main.go
        echo -e "2020 \n" | go run main.go
    - name: TEST Perl files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Perl/main.pl
        echo -e "1 \n" | perl main.pl
        echo -e "2020 \n" | perl main.pl
    - name: TEST Lua files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Lua/main.lua
        echo -e "1 \n" | lua main.lua
        echo -e "2020 \n" | lua main.lua
    - name: Upload Release When Tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            LeapYearCheakLinuxC
            LeapYearCheakLinuxCpp
          name: LeapYearCheak Release ${{ github.ref }}
          body: |
            ## THIS IS THE NEWEST VERSION OF LeapYearCheak!!!!!
            For linux: LeapYearCheakLinuxC LeapYearCheakLinuxCpp
            For windows: LeapYearCheak.C.exe LeapYearCheak.Cpp.exe
            For macos: LeapYearCheakMacC LeapYearCheakMacCpp
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
