name: Linux build 
on: [push,pull_request]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - name: COM Cpp files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/main/Cpp/main.cpp;g++ main.cpp -o LeapYearCheakLinuxCpp
    - name: COM C files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/main/C/main.c;gcc main.c -o LeapYearCheakLinuxC
    - name: Upload Release When Tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            LeapYearCheakLinuxC
            LeapYearCheakLinuxCpp
          name: LeapYearCheak Release ${{ github.ref }}
          body: |
            ## THIS IS THE NEWEST VERSION OF LeapYearCheak!!!!!
            For linux: LeapYearCheakLinuxC LeapYearCheakLinuxCpp
            For windows: LeapYearCheak.C.exe LeapYearCheak.Cpp.exe
            For macos: LeapYearCheakMacC LeapYearCheakMacCpp
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
