name: Linux build for V 2.0
on: [push,pull_request]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
    - name: COM Cpp files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Cpp/main.cpp;g++ main.cpp -o LeapYearCheakLinuxCpp
    - name: COM C files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/C/main.c;gcc main.c -o LeapYearCheakLinuxC
    - name: COM Java files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Java/LeapYearCheak.java;javac LeapYearCheak.java
    - name: COM Swift files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Swift/main.swift;swiftc main.swift
    - name: TEST Python files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Python/main.py
        echo -e "1 \n" | python3 main.py
        echo -e "2020 \n" | python3 main.py
    - name: TEST Go files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Go/main.go
        echo -e "1 \n" | go run main.go
        echo -e "2020 \n" | go run main.go
    - name: Upload Release When Tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            LeapYearCheakLinuxC
            LeapYearCheakLinuxCpp
          name: LeapYearCheak Release ${{ github.ref }}
          body: |
            ## THIS IS THE NEWEST VERSION OF LeapYearCheak!!!!!
            For linux: LeapYearCheakLinuxC LeapYearCheakLinuxCpp
            For windows: LeapYearCheak.C.exe LeapYearCheak.Cpp.exe
            For macos: LeapYearCheakMacC LeapYearCheakMacCpp
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
