name: Linux build for V 2.0
on: [push,pull_request]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
    - name: Setup Mono environment
      run: |
        sudo apt install gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-devel mono-complete
    - name: Setup Swift environment
      run: |
        #wget https://swift.org/builds/swift-5.2.4-release/ubuntu2004/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-ubuntu20.04.tar.gz
        wget https://github.com/xprc/SRD/releases/download/v1.0.0.1/swift-5.2.4-RELEASE-ubuntu20.04.tar.gz
        tar -zxvf swift-5.2.4-RELEASE-ubuntu20.04.tar.gz
    - name: Setup Ruby environment
      run: |
        sudo apt-get install ruby-full
    - name: Setup Pascal environment
      run: |
        sudo apt-get install fp-compiler
    - name: Setup Lua environment
      run: |
        sudo apt install libreadline-dev
        curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz
        tar zxf lua-5.3.5.tar.gz
        cd lua-5.3.5
        sudo make linux test
        sudo make install
    - name: COM Cpp files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Cpp/main.cpp;g++ main.cpp -o LeapYearCheakLinuxCpp
    - name: COM C files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/C/main.c;gcc main.c -o LeapYearCheakLinuxC
    - name: COM Pascal files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Pascal/main.pas
        cp main.pas LeapYearCheakLinuxPascal.pas
        rm main.pas
        fpc LeapYearCheakLinuxPascal.pas
    - name: COM C# files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/CHash/main.cs;mcs main.cs
        cp main.exe LeapYearCheakLinuxCHash.exe
        rm main.exe
    - name: COM Java files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Java/LeapYearCheak.java;javac LeapYearCheak.java
    - name: COM Swift files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Swift/main.swift;./swift-5.2.4-RELEASE-ubuntu20.04/usr/bin/swiftc main.swift
        cp main LeapYearCheakLinuxSwift
        rm main
    - name: TEST Python files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Python/main.py
        echo -e "1 \n" | python3 main.py
        echo -e "2020 \n" | python3 main.py
        cp main.py LeapYearCheak.py
        rm main.py
    - name: TEST Go files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Go/main.go
        echo -e "1 \n" | go run main.go
        echo -e "2020 \n" | go run main.go
        cp main.go LeapYearCheak.go
        rm main.go
    - name: TEST Perl files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Perl/main.pl
        echo -e "1 \n" | perl main.pl
        echo -e "2020 \n" | perl main.pl
        cp main.pl LeapYearCheak.pl
        rm main.pl
    - name: TEST Lua files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Lua/main.lua
        echo -e "1 \n" | lua main.lua
        echo -e "2020 \n" | lua main.lua
        cp main.lua LeapYearCheak.lua
        rm main.lua
    - name: TEST Node.js files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Nodejs/index.js
        echo -e "1 \n" | node index.js
        echo -e "2020 \n" | node index.js
        cp index.js LeapYearCheak.js
        rm index.js
    - name: TEST Ruby files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Ruby/main.rb
        echo -e "1 \n" | ruby main.rb
        echo -e "2020 \n" | ruby main.rb
        cp main.rb LeapYearCheak.rb
        rm main.rb
    - name: GET other files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/HTML5/index.html
        cp index.html LeapYearCheak.html
        rm index.html
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/PHP/index.php
        cp index.php LeapYearCheak.php
        rm index.php
        wget https://github.com/ytmo/LeapYearCheak/archive/2.0.zip
        unzip 2.0.zip
        cd LeapYearCheak-2.0
        cd MacOS-UI
        zip -r MacOSUI-StoryBoard.zip StoryBoard
        zip -r MacOSUI-SwiftUI.zip SwiftUI
        cd ../..
        cp ./LeapYearCheak-2.0/MacOS-UI/MacOSUI-StoryBoard.zip MacOSUI-StoryBoard.zip
        cp ./LeapYearCheak-2.0/MacOS-UI/MacOSUI-SwiftUI.zip MacOSUI-SwiftUI.zip
    - name: Upload Release When Tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            LeapYearCheakLinuxC
            LeapYearCheakLinuxCpp
            LeapYearCheakLinuxCHash.exe
            LeapYearCheakLinuxPascal
            LeapYearCheak.class
            LeapYearCheakLinuxSwift
            LeapYearCheak.py
            LeapYearCheak.go
            LeapYearCheak.pl
            LeapYearCheak.js
            LeapYearCheak.lua
            LeapYearCheak.rb
            LeapYearCheak.php
            LeapYearCheak.html
            MacOSUI-SwiftUI.zip
            MacOSUI-StoryBoard.zip
          name: LeapYearCheak 2.0 Release ${{ github.ref }}
          body: |
            ## THIS IS THE FUTURE VERSION OF LeapYearCheak!!!!!
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
