name: MacOS build for V 2.0
on: [push,pull_request]

jobs:
  build:
    name: Create Release
    runs-on: macOS-latest
    steps:
    - name: COM Cpp files
      run: |
        curl -O  https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Cpp/main.cpp;clang++ main.cpp -o LeapYearCheakMacCpp
    - name: COM C files
      run: |
        curl -O  https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/C/main.c;clang main.c -o LeapYearCheakMacC
    - name: Upload Release When Tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            LeapYearCheakMacC
            LeapYearCheakMacCpp
          name: LeapYearCheak 2.0 Release ${{ github.ref }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
