name: MacOS build for V 2.0
on: [push,pull_request]

jobs:
  build:
    name: Create Release
    runs-on: macOS-latest
    steps:
    - name: Steup Pascal Environment
      run: |
        wget https://github.com/xprc/SRD/releases/download/v1.0.0.0/fpc-3.2.0.intel-macosx.dmg
        sudo installer -pkg fpc-3.2.0-intel-macosx.pkg -target /Application
    - name: COM Cpp files
      run: |
        curl -O  https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Cpp/main.cpp;clang++ main.cpp -o LeapYearCheakMacCpp
    - name: COM C files
      run: |
        curl -O  https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/C/main.c;clang main.c -o LeapYearCheakMacC
    - name: COM Swift files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Swift/main.swift;swiftc main.swift
        cp main LeapYearCheakMacSwift
        rm main
    - name: COM Pascal files
      run: |
        wget https://raw.githubusercontent.com/ytmo/LeapYearCheak/2.0/Pascal/main.pas
        cp main.pas LeapYearCheakMacPascal.pas
        rm main.pas
        fpc LeapYearCheakMacPascal.pas
    - name: Upload Release When Tag
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            LeapYearCheakMacC
            LeapYearCheakMacCpp
            LeapYearCheakMacSwift
            LeapYearCheakMacPascal
          name: LeapYearCheak 2.0 Release ${{ github.ref }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
